name: Print Txt file

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'Choose your server'
        required: true
        type: choice
        default: 'staging'

        options:
          - staging
          - production

jobs:
  print_txt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print User input
        run: | 
          echo "User Input: ${{ github.event.inputs.example_input }}"

      - name: Check the user input
        run: |
          if [ "${{ github.event.inputs.example_input }}" = "staging" ]; then
            echo "You chose staging"
          elif [ "${{ github.event.inputs.example_input }}" = "production" ]; then
            echo "You chose production"
          else
            echo "Invalid input"
            exit 1
          fi

      - name: Print contents of txt file
        run: |
          cat roy.txt



