name: Print Txt file

on:
  workflow_dispatch:

jobs:
  print_txt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print contents of txt file
        run: |
          cat roy.txt



